In [11]:
import pandas as pd
import numpy as np
from interval import interval, inf, imath
pd.set_option("display.max_columns", None)
pd.set_option('display.max_rows', None)

In [12]:
df = pd.read_csv("test_zwischen_erweitert.csv", sep= ";",index_col=0)

In [13]:
df["iou_just_feature"] = np.nan
df["iou_all_feature"] = np.nan
df["iou_alldesc_feature"] = np.nan

In [ ]:
df

,name_of_the_features,id_of_the_features,name_of_the_dataset,datatype_of_the_feature,dataset_min_value,dataset_max_value,data_descr,chat_gpt_just_feature,chat_gpt_all_feature,chat_gpt_desc_feature,just_feature_min_value,just_feature_max_value,all_feature_min_value,all_feature_max_value,all_feature_min_value_desc,all_feature_max_value_desc,iou_just_feature,iou_all_feature,iou_alldesc_feature
0,RIDGE,871,pollen,numeric,-2.328390e+01,2.140660e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: 0.5\nMaximum: 10.0,The range of values for the feature RIDGE is u...,NaN,NaN,0.50,1.000000e+01,NaN,NaN,NaN,2.125731e-01,NaN
1,NUB,871,pollen,numeric,-1.639350e+01,1.725830e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: 0\nMaximum: 1,"The range of values for the feature ""NUB"" is n...",NaN,NaN,0.00,1.000000e+00,NaN,NaN,NaN,2.971609e-02,NaN
2,CRACK,871,pollen,numeric,-3.141300e+01,3.031780e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: 0\nMaximum: 10,The range of values for the feature CRACK in t...,NaN,NaN,0.00,1.000000e+01,0.000000,1.000000e+00,NaN,1.619937e-01,0.016199
3,WEIGHT,871,pollen,numeric,-3.403520e+01,3.580280e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: Unknown\nMaximum: Unknown,"Unfortunately, without access to the actual da...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DENSITY,871,pollen,numeric,-1.203910e+01,1.086730e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: 0.05\nMaximum: 1.0,"Without access to the dataset, it is not possi...",NaN,NaN,0.05,1.000000e+00,NaN,NaN,NaN,4.147313e-02,NaN
5,a1,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Minimum: Unknown\nMaximum: Unknown,The range of values for feature a1 is not prov...,NaN,NaN,NaN,NaN,1.000000,5.000000e-01,NaN,NaN,0.500000
6,a2,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,"minimum: unknown, maximum: unknown.",The range of values for the feature a2 is not ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,a3,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Minimum: Unknown\nMaximum: Unknown,Based on the information provided the range of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,a4,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Minimum: Unknown\nMaximum: Unknown,The minimum and maximum values for feature a4 ...,NaN,NaN,NaN,NaN,4.000000,5.000000e-01,NaN,NaN,0.125000
9,a5,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Minimum: unknown\nMaximum: unknown,The min and max values for the feature a5 are ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,y1,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Unfortunately as an AI language model I cannot...,Based on the dataset the range of values for t...,NaN,NaN,1.00,1.000000e+00,1.000000,1.000000e+00,NaN,0.000000e+00,0.000000
11,y2,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,Minimum: -10\nMaximum: 10,Minimum: Unknown\nMaximum: Unknown,Based on the information provided the range of...,-10.0,1.000000e+01,NaN,NaN,NaN,NaN,0.050000,NaN,NaN
12,productId,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 1000\nMaximum: 9999,Minimum: 1\nMaximum: 100000,Min: productId = 1\nMax: productId = 10000,1000.0,9.999000e+03,1.00,1.000000e+05,1.000000,1.000000e+04,NaN,0.000000e+00,0.000000
13,machineId,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 1\nMaximum: 10000,Minimum: 1000\nMaximum: 5000,The minimum and maximum values for the feature...,1.0,1.000000e+04,1000.00,5.000000e+03,NaN,NaN,0.000000,NaN,NaN
14,temp,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,temp: -10 to 40,Minimum: -100 degrees Celsius\nMaximum: 100 de...,"The range of values for the feature ""temp"" in ...",-10.0,4.000000e+01,-100.00,1.000000e+02,NaN,NaN,0.020000,5.000000e-03,NaN
15,weather_condition_id,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 1\nMaximum: 10,Minimum: 1\nMaximum: 10,"Based on the given dataset, the range of value...",1.0,1.000000e+01,1.00,1.000000e+01,NaN,NaN,0.000000,0.000000e+00,NaN
16,isholiday,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 0\nMaximum: 1,Minimum: 0 (assuming 0 represents not a holida...,The minimum and maximum values for the feature...,0.0,1.000000e+00,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
17,daysoff,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 0 Maximum: 365,Minimum: 0\nMaximum: 365,"Based on the given dataset, the range of value...",0.0,3.650000e+02,0.00,3.650000e+02,NaN,NaN,0.002740,2.739726e-03,NaN
18,year,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 2000\nMaximum: 2022,Minimum: 2000 Maximum: 2025,"Based on the given dataset description, the ra...",2000.0,2.022000e+03,2000.00,2.025000e+03,NaN,NaN,NaN,NaN,NaN
19,month,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: January\nMaximum: December,Minimum: 1\nMaximum: 12,min(month): 1\nmax(month): 12,NaN,NaN,1.00,1.200000e+01,1.000000,1.200000e+01,NaN,0.000000e+00,0.000000
20,day,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 1\nMaximum: 31,Minimum: 1\nMaximum: 31,The minimum and maximum values for the feature...,1.0,3.100000e+01,1.00,3.100000e+01,NaN,NaN,0.000000,0.000000e+00,NaN
21,week_day,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Dataset: \n\nweek_day: [1 2 3 4 5 6 7]\n\nMini...,Minimum: 1\nMaximum: 7,min: Monday\nmax: Sunday,NaN,NaN,1.00,7.000000e+00,NaN,NaN,NaN,0.000000e+00,NaN
22,avail0,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,NaN,Minimum: 0\nMaximum: 1,"For the feature ""avail0"" in the sales dataset ...",NaN,NaN,0.00,1.000000e+00,NaN,NaN,NaN,1.000000e+00,NaN
23,avail1,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Based on the available dataset the minimum and...,Minimum: 0\nMaximum: 1,min(avail1): 0\nmax(avail1): 1,NaN,NaN,0.00,1.000000e+00,NaN,NaN,NaN,1.000000e+00,NaN
24,avail2,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,min: 0 max: 1,Minimum: 0\nMaximum: 1,min: avail2 = min value in the dataset sales\n...,0.0,1.000000e+00,0.00,1.000000e+00,2.000000,2.000000e+00,1.000000,1.000000e+00,NaN
25,sales,42183,dataset_sales,numeric,3.000000e+00,8.500000e+01,Dataset sales,Minimum: 0\nMaximum: 1000000,Minimum: 0\nMaximum: Unknown,The minimum and maximum values for the feature...,0.0,1.000000e+06,NaN,NaN,NaN,NaN,0.000082,NaN,NaN
26,stdv,42183,dataset_sales,numeric,0.000000e+00,4.700000e+01,Dataset sales,min stdv: 0.1\nmax stdv: 4.5,Minimum value: 0.0\nMaximum value: 1.0,For the feature stdv the minimum value is 0 an...,0.1,4.500000e+00,0.00,1.000000e+00,NaN,NaN,0.093617,2.127660e-02,NaN
27,qts,42545,stock_fardamento02,numeric,1.000000e+00,8.330000e+02,**Author**: \n\n**Source**: Unknown - Date u...,Minimum: 0\nMaximum: 100,Min: Unknown\nMax: Unknown,min: 0\nmax: unknown,0.0,1.000000e+02,NaN,NaN,NaN,NaN,0.118848,NaN,NaN
28,Material,42545,stock_fardamento02,numeric,5.367000e+03,6.502400e+04,**Author**: \n\n**Source**: Unknown - Date u...,Min: 1\nMax: 10,Minimum: Unknown\nMaximum: Unknown,"Sorry, but I can't generate a range of values ...",1.0,1.000000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,pp,42545,stock_fardamento02,numeric,0.000000e+00,2.010000e+01,**Author**: \n\n**Source**: Unknown - Date u...,Range: 0 to 1000,Minimum: unknown\nMaximum: unknown,"pp: min = Unknown, max = Unknown",0.0,1.000000e+03,NaN,NaN,NaN,NaN,0.020100,NaN,NaN
30,TEMP,42545,stock_fardamento02,numeric,8.400000e+00,2.600000e+01,**Author**: \n\n**Source**: Unknown - Date u...,Minimum: -10°C\nMaximum: 40°C,The range of values for the feature TEMP in th...,"TEMP: min = unknown, max = unknown",-10.0,4.000000e+01,NaN,NaN,NaN,NaN,0.352000,NaN,NaN
31,adm,42545,stock_fardamento02,numeric,2.800000e+01,2.300000e+02,**Author**: \n\n**Source**: Unknown - Date u...,Minimum: 0\nMaximum: 100,Minimum: Unknown\nMaximum: Unknown,"The range of values for the feature ""adm"" is m...",0.0,1.000000e+02,NaN,NaN,NaN,NaN,0.313043,NaN,NaN
32,Dem,42545,stock_fardamento02,numeric,3.600000e+01,2.390000e+02,**Author**: \n\n**Source**: Unknown - Date u...,Min: 0 \nMax: 100,"min(Dem) = ???, max(Dem) = ???","The range of values for the feature ""Dem"" is n...",0.0,1.000000e+02,NaN,NaN,NaN,NaN,0.267782,NaN,NaN
33,1990,43809,GDP-per-capita-all-countries,numeric,4.248240e+02,7.290652e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: unknown\nMaximum: unknown,"1990: [unknown minimum value, unknown maximum ...","To set a range of values for the feature ""1990...",NaN,NaN,NaN,NaN,1990.000000,1.990000e+03,NaN,NaN,0.000000
34,1991,43809,GDP-per-capita-all-countries,numeric,3.246360e+02,7.175373e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1900\nMaximum: 2021,1991: Min Value = 1991 Max Value = 1991,min: 1991\nmax: 2019,1900.0,2.021000e+03,NaN,NaN,1991.000000,2.019000e+03,0.001694,NaN,0.000392
35,1992,43809,GDP-per-capita-all-countries,numeric,3.009790e+02,7.156783e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum value: 0\nMaximum value: 1000,Minimum: 1992\nMaximum: 1992,The dataset provides the GDP values for the ye...,0.0,1.000000e+03,1992.00,1.992000e+03,1992.000000,1.992000e+03,0.009767,0.000000e+00,0.000000
36,1993,43809,GDP-per-capita-all-countries,numeric,3.273412e+02,7.008239e+04,Gross Domestic Product (GDP) is the monetary v...,NaN,Minimum: 1993\nMaximum: 1993,"The range of values for the feature ""1993"" is ...",NaN,NaN,1993.00,1.993000e+03,NaN,NaN,NaN,0.000000e+00,NaN
37,1994,43809,GDP-per-capita-all-countries,numeric,3.424329e+02,7.247169e+04,Gross Domestic Product (GDP) is the monetary v...,1994: min = 0 max = 99999999,Minimum: 1994\nMaximum: 1994,The range of values for the feature 1994 in th...,NaN,NaN,1994.00,1.994000e+03,NaN,NaN,NaN,0.000000e+00,NaN
38,1995,43809,GDP-per-capita-all-countries,numeric,3.451363e+02,7.499438e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1995\nMaximum: 1995,Minimum: 1995\nMaximum: 1995,min: 1995\nmax: 1995,1995.0,1.995000e+03,1995.00,1.995000e+03,1995.000000,1.995000e+03,0.000000,0.000000e+00,0.000000
39,1996,43809,GDP-per-capita-all-countries,numeric,3.791511e+02,7.684879e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1\nMaximum: 9999,Minimum: 1996\nMaximum: 1996,"The range of values for the feature ""1996"" in ...",1.0,9.999000e+03,1996.00,1.996000e+03,NaN,NaN,0.125181,0.000000e+00,NaN
40,1997,43809,GDP-per-capita-all-countries,numeric,4.178392e+02,8.039006e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1997\nMaximum: 1997,1997: min = 1997 max = 1997.,min: 1997\nmax: 1997,1997.0,1.997000e+03,NaN,NaN,1997.000000,1.997000e+03,0.000000,NaN,0.000000
41,1998,43809,GDP-per-capita-all-countries,numeric,4.526621e+02,7.742111e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 10000,Minimum: 1998\nMaximum: 1998,Min: 1998\nMax: 1998,0.0,1.000000e+04,1998.00,1.998000e+03,1998.000000,1.998000e+03,0.123317,0.000000e+00,0.000000
42,1999,43809,GDP-per-capita-all-countries,numeric,4.691280e+02,7.665426e+04,Gross Domestic Product (GDP) is the monetary v...,Min: 1990\nMax: 2010,1999: min=1999 max=1999,The minimum and maximum values for the feature...,1990.0,2.010000e+03,NaN,NaN,NaN,NaN,0.000263,NaN,NaN
43,2000,43809,GDP-per-capita-all-countries,numeric,4.558151e+02,8.616939e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1500\nMaximum: 2500,Minimum: 2000\nMaximum: 2019,The range of values for the feature 2000 from ...,1500.0,2.500000e+03,2000.00,2.019000e+03,NaN,NaN,0.011667,2.216685e-04,NaN
44,2001,43809,GDP-per-capita-all-countries,numeric,4.435747e+02,8.813842e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1\nMaximum: 3000,Minimum: 2001 \nMaximum: 2001,The minimum and maximum values for the feature...,1.0,3.000000e+03,2001.00,2.001000e+03,NaN,NaN,0.029005,0.000000e+00,NaN
45,2002,43809,GDP-per-capita-all-countries,numeric,4.504504e+02,9.209128e+04,Gross Domestic Product (GDP) is the monetary v...,Min: 0\nMax: 100,Minimum: 2002\nMaximum: 2002,The range of values for the feature 2002 is: M...,0.0,1.000000e+02,2002.00,2.002000e+03,NaN,NaN,NaN,0.000000e+00,NaN
46,2003,43809,GDP-per-capita-all-countries,numeric,4.697704e+02,9.145161e+04,Gross Domestic Product (GDP) is the monetary v...,2003: Minimum value: unknown. Maximum value: u...,Minimum: 2003\nMaximum: 2003,Based on the dataset provided the range of val...,NaN,NaN,2003.00,2.003000e+03,NaN,NaN,NaN,0.000000e+00,NaN
47,2004,43809,GDP-per-capita-all-countries,numeric,4.989799e+02,1.013295e+05,Gross Domestic Product (GDP) is the monetary v...,NaN,Minimum: 2004\nMaximum: 2004,Min: 2004\nMax: 2004,NaN,NaN,2004.00,2.004000e+03,2004.000000,2.004000e+03,NaN,0.000000e+00,0.000000
48,2005,43809,GDP-per-capita-all-countries,numeric,5.289748e+02,9.776857e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100,Minimum: 2005\nMaximum: 2005,Min: 2005\nMax: 2005,0.0,1.000000e+02,2005.00,2.005000e+03,2005.000000,2.005000e+03,NaN,0.000000e+00,0.000000
49,2006,43809,GDP-per-capita-all-countries,numeric,5.558000e+02,1.075415e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 1000000,Minimum: 2006\nMaximum: 2006,The min and max values for the feature 2006 fr...,0.0,1.000000e+06,2006.00,2.006000e+03,NaN,NaN,0.106986,0.000000e+00,NaN
50,2007,43809,GDP-per-capita-all-countries,numeric,5.869953e+02,1.093625e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 2007\nMaximum: 2007,Minimum: 2007\nMaximum: 2007,Min: 485415.9\nMax: 21345493.9,2007.0,2.007000e+03,2007.00,2.007000e+03,485415.900000,2.134549e+07,0.000000,0.000000e+00,NaN
51,2008,43809,GDP-per-capita-all-countries,numeric,6.150720e+02,1.112560e+05,Gross Domestic Product (GDP) is the monetary v...,"The minimum value for the feature ""2008"" is: u...",Minimum: 2008\nMaximum: 2008,Min: 2008\nMax: 2008,NaN,NaN,2008.00,2.008000e+03,2008.000000,2.008000e+03,NaN,0.000000e+00,0.000000
52,2009,43809,GDP-per-capita-all-countries,numeric,6.166586e+02,1.089537e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100000,Min: 2009\nMax: 2009,Based on the given dataset the range of values...,0.0,1.000000e+05,2009.00,2.009000e+03,NaN,NaN,0.912161,0.000000e+00,NaN
53,2010,43809,GDP-per-capita-all-countries,numeric,6.462954e+02,1.175187e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100000,2010: min = 2010 max = 2010,Based on the given dataset description we can ...,0.0,1.000000e+05,NaN,NaN,2010.000000,2.010000e+03,0.845429,NaN,0.000000
54,2011,43809,GDP-per-capita-all-countries,numeric,6.820073e+02,1.240246e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 99999,Minimum: 2011\nMaximum: 2011,Min: 2011 Max: 2011,0.0,9.999900e+04,2011.00,2.011000e+03,2011.000000,2.011000e+03,0.800785,0.000000e+00,0.000000
55,2012,43809,GDP-per-capita-all-countries,numeric,7.199143e+02,1.266184e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100,Minimum: 2012\nMaximum: 2012,"The range of values for the feature ""2012"" in ...",0.0,1.000000e+02,2012.00,2.012000e+03,NaN,NaN,NaN,0.000000e+00,NaN
56,2013,43809,GDP-per-capita-all-countries,numeric,6.995929e+02,1.399622e+05,Gross Domestic Product (GDP) is the monetary v...,Min: 0\nMax: 100,Minimum: 2013\nMaximum: 2013,"The range of values for the feature ""2013"" can...",0.0,1.000000e+02,2013.00,2.013000e+03,NaN,NaN,NaN,0.000000e+00,NaN
57,2014,43809,GDP-per-capita-all-countries,numeric,7.108122e+02,1.378330e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100,Minimum: 2014\nMaximum: 2014,"The range of values for the feature ""2014"" in ...",0.0,1.000000e+02,2014.00,2.014000e+03,2014.000000,2.014000e+03,NaN,0.000000e+00,0.000000
58,2015,43809,GDP-per-capita-all-countries,numeric,7.447345e+02,1.238221e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100,Minimum: 2015\nMaximum: 2015,"The range of values for the feature ""2015"" in ...",0.0,1.000000e+02,2015.00,2.015000e+03,NaN,NaN,NaN,0.000000e+00,NaN
59,2016,43809,GDP-per-capita-all-countries,numeric,7.439036e+02,1.235736e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: Unknown\nMaximum: Unknown,Minimum: 2016\nMaximum: 2016,"The range of values for the feature ""2016"" in ...",NaN,NaN,2016.00,2.016000e+03,NaN,NaN,NaN,0.000000e+00,NaN
60,2017,43809,GDP-per-capita-all-countries,numeric,7.379786e+02,1.246093e+05,Gross Domestic Product (GDP) is the monetary v...,min: 0\nmax: 100,Min: 2017\nMax: 2017,To set a range of values for the feature 2017 ...,0.0,1.000000e+02,2017.00,2.017000e+03,NaN,NaN,NaN,0.000000e+00,NaN
61,2018,43809,GDP-per-capita-all-countries,numeric,7.441821e+02,1.268984e+05,Gross Domestic Product (GDP) is the monetary v...,The minimum and maximum values for the feature...,Min: 2018 Max: 2018,Min: 1990\nMax: 2019,NaN,NaN,2018.00,2.018000e+03,1990.000000,2.019000e+03,NaN,0.000000e+00,0.000230
62,2019,43809,GDP-per-capita-all-countries,numeric,NaN,NaN,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100000,Min: 2019\nMax: 2019,To determine the range of values for the featu...,0.0,1.000000e+05,2019.00,2.019000e+03,NaN,NaN,0.000000,0.000000e+00,NaN
63,Unnamed:_0,43825,Nutritional-values-for-common-foods-and-products,numeric,0.000000e+00,8.788000e+03,Context\nI found this data occasionally and I ...,min: -∞\nmax: +∞,Minimum: 0\nMaximum: Unknown,"The range of values for the feature ""Unnamed:_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,calories,43825,Nutritional-values-for-common-foods-and-products,numeric,0.000000e+00,9.020000e+02,Context\nI found this data occasionally and I ...,Minimum: 0\nMaximum: 5000,"min(calories), max(calories)","The range of values for the feature ""calories""...",0.0,5.000000e+03,NaN,NaN,NaN,NaN,0.180400,NaN,NaN
65,lucopene,43825,Nutritional-values-for-common-foods-and-products,numeric,0.000000e+00,0.000000e+00,Context\nI found this data occasionally and I ...,Minimum: 0\nMaximum: 5000,Minimum: 0\nMaximum: Unknown (Not provided in ...,Min: 0.0\n\nMax: 2181.0,0.0,5.000000e+03,NaN,NaN,0.000000,2.181000e+03,0.000000,NaN,0.000000
66,Year,43831,Consumer-Price-Index,numeric,2.013000e+03,2.020000e+03,Consumer Price Indices (CPI) measure changes o...,Min: 2000 Max: 2021,Minimum: Year 0 (assuming it starts from year ...,"Based on the provided dataset, the range of va...",2000.0,2.021000e+03,NaN,NaN,NaN,NaN,0.333333,NaN,NaN
67,Cereals_and_products,43831,Consumer-Price-Index,numeric,1.075000e+02,1.527000e+02,Consumer Price Indices (CPI) measure changes o...,Minimum: 0\nMaximum: 100,"Min: 0, Max: Unlimited",Min: 0.00 \nMax: 600.00,0.0,1.000000e+02,NaN,NaN,0.000000,6.000000e+02,NaN,NaN,0.075333
68,Meat_and_fish,43831,Consumer-Price-Index,numeric,1.063000e+02,1.970000e+02,Consumer Price Indices (CPI) measure changes o...,Minimum: 0\nMaximum: 10000,Minimum: 0\nMaximum: Not provided,"Min: The minimum value for the feature ""Meat_a...",0.0,1.000000e+04,NaN,NaN,NaN,NaN,0.009070,NaN,NaN
69,Egg,43831,Consumer-Price-Index,numeric,1.027000e+02,1.570000e+02,Consumer Price Indices (CPI) measure changes o...,Minimum: 0\nMaximum: 200,Minimum: 0\nMaximum: Unknown,"The range of values for the feature ""Egg"" in t...",0.0,2.000000e+02,NaN,NaN,NaN,NaN,0.271500,NaN,NaN
70,Milk_and_products,43831,Consumer-Price-Index,numeric,1.036000e+02,1.556000e+02,Consumer Price Indices (CPI) measure changes o...,Minimum: 0\nMaximum: 30000,Minimum: 0 \nMaximum: Unknown,Min: 0\nMax: 100,0.0,3.000000e+04,NaN,NaN,0.000000,1.000000e+02,0.001733,NaN,NaN

In [110]:
df.id_of_the_features.nunique()

28

In [29]:
df.dataset_min_value.value_counts()

 0.000000e+00    122
 1.000000e+00     28
 2.000000e+00     10
 2.844950e-04      8
 2.891850e-04      5
 1.800000e+01      4
 3.000000e+00      4
 2.000000e+01      4
 5.000000e+00      3
 2.907820e-04      3
 1.000000e-01      3
 1.500000e+01      2
 6.000000e+00      2
 4.900000e+01      2
 2.018000e+03      2
 1.048000e+02      2
 9.500000e+02      2
 5.000000e+01      2
 4.000000e+00      2
 1.035000e+02      2
 1.040000e+02      2
-4.364381e+00      1
 1.001000e+03      1
 3.424329e+02      1
 8.630000e-01      1
 7.441821e+02      1
-2.651890e+02      1
-3.617918e+00      1
-4.578622e+00      1
 7.379786e+02      1
-3.806062e+00      1
 1.398000e+00      1
 1.713911e+00      1
 3.637586e+00      1
 4.035000e+02      1
-2.743479e+00      1
 8.090000e+02      1
-2.356192e+00      1
-3.712649e+00      1
 3.009790e+02      1
-2.355579e+00      1
-3.741948e+00      1
 3.197040e+01      1
-3.650459e+00      1
 2.500787e-01      1
 2.501547e-01      1
 7.439036e+02      1
-2.355884e+00      1
-7.499401e+01      1
-3.403520e+01      1
 8.530000e+01      1
 3.194902e+05      1
 1.067000e+02      1
-3.434010e+00      1
 8.039000e-01      1
 1.118000e+00      1
 1.003000e+02      1
-7.498539e+01      1
-3.503835e+00      1
 5.289748e+02      1
-3.550759e+00      1
 6.166586e+02      1
 4.248240e+02      1
 3.273412e+02      1
 7.447345e+02      1
 5.000000e-04      1
-3.998474e+00      1
 3.451363e+02      1
 8.400000e+00      1
 1.063000e+02      1
 6.612400e+02      1
-1.135172e-01      1
-3.829966e+00      1
 9.900000e-01      1
 7.937000e+01      1
 3.762592e+01      1
-3.577676e+00      1
 2.500365e-01      1
 4.697704e+02      1
 1.400000e+01      1
 8.000000e+00      1
 9.000000e+00      1
 7.000000e+00      1
-3.860000e+01      1
 4.700000e+01      1
 1.550000e+02      1
 1.600000e+01      1
 5.000000e+02      1
 5.000000e-01      1
 4.991562e+01      1
-1.203910e+01      1
 4.800000e+01      1
-4.102300e+01      1
 1.200000e+01      1
-3.000000e+00      1
 3.500000e+02      1
 1.100000e+01      1
 6.462954e+02      1
-1.450000e+01      1
-2.350000e+01      1
-3.750000e+01      1
 1.050000e+02      1
 1.055000e+02      1
 1.075000e+02      1
 3.600000e+01      1
 2.800000e+01      1
 1.022000e+00      1
 2.500000e+01      1
 6.400000e+01      1
 2.810000e-07      1
 4.369448e+00      1
 2.507491e-01      1
-3.526863e+00      1
-3.848386e+00      1
 5.558000e+02      1
-3.706062e+00      1
 1.037000e+02      1
 1.158000e+01      1
 1.544000e+00      1
-1.206000e+00      1
 7.586804e+00      1
 2.511707e+07      1
-4.113898e+00      1
 6.500000e+01      1
 2.504344e-01      1
 4.178392e+02      1
 2.505210e-01      1
-1.056000e+01      1
-4.006246e+00      1
 2.500824e-01      1
-3.781449e+00      1
-3.776095e+00      1
-6.557422e+00      1
-2.372783e+00      1
-3.980000e-01      1
 2.500922e-01      1
 1.522800e+01      1
-2.355918e+00      1
-3.388576e+00      1
-1.639350e+01      1
-7.499611e+01      1
-3.780620e+00      1
-3.357140e+00      1
 1.029000e+02      1
-3.798011e+00      1
-3.141300e+01      1
 6.150720e+02      1
 3.135494e+00      1
-3.844106e+00      1
 2.554261e+00      1
-2.355893e+00      1
-3.286132e+00      1
 1.054000e+02      1
 9.060900e+04      1
-1.918000e+03      1
-3.743000e+03      1
 5.367000e+03      1
-2.355979e+00      1
 9.250000e-02      1
-4.085853e+00      1
-4.050889e+00      1
 1.370000e-01      1
 4.691280e+02      1
 1.059000e+02      1
 1.467000e+00      1
-3.832277e+00      1
 4.504504e+02      1
-3.090000e+01      1
 2.501434e-01      1
-2.740000e+01      1
 1.023000e+02      1
 6.820073e+02      1
-5.256000e+00      1
 1.027000e+02      1
-3.057045e+00      1
-3.046482e+00      1
-1.099000e+00      1
 4.440000e-01      1
-3.130000e+01      1
-2.355641e+00      1
 9.570000e-01      1
 3.952043e+01      1
 2.500895e-01      1
 1.510000e+01      1
 4.917000e+00      1
 2.502136e-01      1
-4.170000e+01      1
 5.260000e-01      1
-6.336000e+01      1
-2.470000e+01      1
 6.027031e+01      1
 1.032000e+02      1
 1.031010e+01      1
-2.328390e+01      1
 2.504841e-01      1
-3.714059e+00      1
 1.058000e+02      1
-3.060000e+01      1
-3.673687e+00      1
-3.903017e+00      1
 4.697947e+01      1
-3.979526e+00      1
 1.018000e+02      1
 1.062800e+04      1
 4.558151e+02      1
-4.080000e+01      1
 1.111076e+01      1
 4.526621e+02      1
 2.392050e+03      1
-3.828703e+00      1
-4.407334e+00      1
-2.356149e+00      1
 1.147023e+01      1
-3.747531e+00      1
-4.810000e+01      1
 8.306982e+01      1
 4.174000e+00      1
 1.428571e-02      1
 2.505092e-01      1
-2.356155e+00      1
-2.355378e+00      1
-2.917722e+00      1
 1.340193e+02      1
 1.950000e+03      1
 1.144000e+00      1
-2.461000e+03      1
-4.325500e+00      1
-4.004914e+00      1
 3.246360e+02      1
-2.130000e+01      1
 7.108122e+02      1
 2.267000e+00      1
 4.989799e+02      1
 3.791511e+02      1
 4.400000e-01      1
-6.311427e+00      1
-2.355764e+00      1
-3.559484e+00      1
-1.180634e+01      1
 9.891578e+00      1
 1.021000e+02      1
-2.356092e+00      1
 1.051000e+02      1
 2.506534e-01      1
 1.011000e+02      1
 1.014000e+02      1
 1.036000e+02      1
-1.203816e+04      1
 5.328000e+01      1
-7.498643e+01      1
 3.406968e+03      1
-3.653304e+00      1
 2.503663e-01      1
 5.869953e+02      1
 2.013000e+03      1
 4.435747e+02      1
 7.199143e+02      1
-3.937435e+00      1
-3.329408e+00      1
-3.510998e+00      1
-7.499187e+01      1
-4.076485e+00      1
 1.188000e+00      1
-1.242299e+08      1
-2.732906e+00      1
 1.509553e+03      1
 6.995929e+02      1
-3.813526e+00      1
 7.700000e+00      1
 5.415358e-03      1
Name: dataset_min_value, dtype: int64

## Calculation of JI

In [14]:
def jaccard_t1(i):
    print(i)
    if np.isnan(df["just_feature_min_value"][i]):
       return np.NaN
    if np.isnan(df["just_feature_max_value"][i]):
       return np.NaN
    
    i1= interval([df["dataset_min_value"][i] , df["dataset_max_value"][i]])
    
    i2 = interval([df["just_feature_min_value"][i]  , df["just_feature_max_value"][i]])
    u = i1 | i2
    it =i1 & i2
    
    try:
        

        un1= u[0][1]-u[0][0]
        if len(it) == 0:
            
            np.NaN
        else:

            inter1= it[0][1]-it[0][0]

        if un1 == 0:
            return np.NaN
        else:
            
            iou=inter1/un1
            
        return iou
    
    except:
    
        return np.NaN

In [15]:
for i in range(0,len(df)):
    
    jac = jaccard_t1(i)
    df["iou_just_feature"][i] = jac

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463

/var/folders/g5/1dssy_112cz_1wxrtkxbnzjc0000gn/T/ipykernel_58096/4158639136.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
def jaccard_t2(i):
    
    if np.isnan(df["all_feature_min_value"][i]):
       return np.NaN
    if np.isnan(df["all_feature_max_value"][i]):
       return np.NaN
    
    i1= interval([df["dataset_min_value"][i] , df["dataset_max_value"][i]])
    
    i2 = interval([df["all_feature_min_value"][i]  , df["all_feature_max_value"][i]])
    
    u = i1 | i2
    it =i1 & i2
    
    try:
    
        
        un1= u[0][1]-u[0][0]
        if len(it) == 0:
            
            return np.NaN
        else:

            inter1= it[0][1]-it[0][0]
        
        
        if un1 == 0:
            return np.NaN
        else:
            
            
            iou=inter1/un1
        
        
        return iou
    
    except:
        
        return np.NaN

In [17]:
for i in range(0,len(df)):
    
    jac = jaccard_t2(i)
    df["iou_all_feature"][i] = jac

/var/folders/g5/1dssy_112cz_1wxrtkxbnzjc0000gn/T/ipykernel_58096/1655199371.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [18]:
def jaccard_t3(i):
    
    if np.isnan(df["all_feature_min_value_desc"][i]):
       return np.NaN
    if np.isnan(df["all_feature_max_value_desc"][i]):
       return np.NaN
    
    i1= interval([df["dataset_min_value"][i] , df["dataset_max_value"][i]])
    
    i2 = interval([df["all_feature_min_value_desc"][i]  , df["all_feature_max_value_desc"][i]])
    
    u = i1 | i2
    it =i1 & i2
    
    try:
    
        
        un1= u[0][1]-u[0][0]
        if len(it) == 0:
            
            return np.NaN
        else:

            inter1= it[0][1]-it[0][0]
        
        
        if un1 == 0:
            return np.NaN
        else:
            
            
            iou=inter1/un1
        
        
        return iou
    
    except:
        
        return np.NaN

In [19]:
for i in range(0,len(df)):
    
    jac = jaccard_t3(i)
    df["iou_alldesc_feature"][i] = jac

/var/folders/g5/1dssy_112cz_1wxrtkxbnzjc0000gn/T/ipykernel_58096/1587523102.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [106]:
exp1 = df.iou_just_feature.dropna()
exp1.mean()

0.37665213585561513

In [107]:
exp2=df.iou_all_feature.dropna()
exp2.mean()

0.5280455743533351

In [108]:
exp3= df.iou_alldesc_feature.dropna()
exp3.mean()

0.5369242040503052

In [13]:
df

,name_of_the_features,id_of_the_features,name_of_the_dataset,datatype_of_the_feature,dataset_min_value,dataset_max_value,data_descr,chat_gpt_just_feature,chat_gpt_all_feature,chat_gpt_desc_feature,just_feature_min_value,just_feature_max_value,all_feature_min_value,all_feature_max_value,all_feature_min_value_desc,all_feature_max_value_desc,iou_just_feature,iou_all_feature,iou_alldesc_feature
0,RIDGE,871,pollen,numeric,-2.328390e+01,2.140660e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: 0.5\nMaximum: 10.0,The range of values for the feature RIDGE is u...,NaN,NaN,0.50,1.000000e+01,NaN,NaN,NaN,0.212573,NaN
1,NUB,871,pollen,numeric,-1.639350e+01,1.725830e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: 0\nMaximum: 1,"The range of values for the feature ""NUB"" is n...",NaN,NaN,0.00,1.000000e+00,NaN,NaN,NaN,0.029716,NaN
2,CRACK,871,pollen,numeric,-3.141300e+01,3.031780e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: 0\nMaximum: 10,The range of values for the feature CRACK in t...,NaN,NaN,0.00,1.000000e+01,0.000000,1.000000e+00,NaN,0.161994,0.016199
3,WEIGHT,871,pollen,numeric,-3.403520e+01,3.580280e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: Unknown\nMaximum: Unknown,"Unfortunately, without access to the actual da...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DENSITY,871,pollen,numeric,-1.203910e+01,1.086730e+01,**Author**: \n**Source**: Unknown - Date unk...,NaN,Minimum: 0.05\nMaximum: 1.0,"Without access to the dataset, it is not possi...",NaN,NaN,0.05,1.000000e+00,NaN,NaN,NaN,0.041473,NaN
5,a1,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Minimum: Unknown\nMaximum: Unknown,The range of values for feature a1 is not prov...,NaN,NaN,NaN,NaN,1.000000,5.000000e-01,NaN,NaN,0.500000
6,a2,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,"minimum: unknown, maximum: unknown.",The range of values for the feature a2 is not ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,a3,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Minimum: Unknown\nMaximum: Unknown,Based on the information provided the range of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,a4,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Minimum: Unknown\nMaximum: Unknown,The minimum and maximum values for feature a4 ...,NaN,NaN,NaN,NaN,4.000000,5.000000e-01,NaN,NaN,0.125000
9,a5,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Minimum: unknown\nMaximum: unknown,The min and max values for the feature a5 are ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,y1,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,NaN,Unfortunately as an AI language model I cannot...,Based on the dataset the range of values for t...,NaN,NaN,1.00,1.000000e+00,1.000000,1.000000e+00,NaN,0.000000,0.000000
11,y2,23515,sulfur,numeric,0.000000e+00,1.000000e+00,&quot;The sulfur recovery unit (SRU) removes e...,Minimum: -10\nMaximum: 10,Minimum: Unknown\nMaximum: Unknown,Based on the information provided the range of...,-10.0,1.000000e+01,NaN,NaN,NaN,NaN,0.050000,NaN,NaN
12,productId,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 1000\nMaximum: 9999,Minimum: 1\nMaximum: 100000,Min: productId = 1\nMax: productId = 10000,1000.0,9.999000e+03,1.00,1.000000e+05,1.000000,1.000000e+04,NaN,0.000000,0.000000
13,machineId,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 1\nMaximum: 10000,Minimum: 1000\nMaximum: 5000,The minimum and maximum values for the feature...,1.0,1.000000e+04,1000.00,5.000000e+03,NaN,NaN,0.000000,NaN,NaN
14,temp,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,temp: -10 to 40,Minimum: -100 degrees Celsius\nMaximum: 100 de...,"The range of values for the feature ""temp"" in ...",-10.0,4.000000e+01,-100.00,1.000000e+02,NaN,NaN,0.020000,0.005000,NaN
15,weather_condition_id,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 1\nMaximum: 10,Minimum: 1\nMaximum: 10,"Based on the given dataset, the range of value...",1.0,1.000000e+01,1.00,1.000000e+01,NaN,NaN,0.000000,0.000000,NaN
16,isholiday,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 0\nMaximum: 1,Minimum: 0 (assuming 0 represents not a holida...,The minimum and maximum values for the feature...,0.0,1.000000e+00,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
17,daysoff,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 0 Maximum: 365,Minimum: 0\nMaximum: 365,"Based on the given dataset, the range of value...",0.0,3.650000e+02,0.00,3.650000e+02,NaN,NaN,0.002740,0.002740,NaN
18,year,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 2000\nMaximum: 2022,Minimum: 2000 Maximum: 2025,"Based on the given dataset description, the ra...",2000.0,2.022000e+03,2000.00,2.025000e+03,NaN,NaN,NaN,NaN,NaN
19,month,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: January\nMaximum: December,Minimum: 1\nMaximum: 12,min(month): 1\nmax(month): 12,NaN,NaN,1.00,1.200000e+01,1.000000,1.200000e+01,NaN,0.000000,0.000000
20,day,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Minimum: 1\nMaximum: 31,Minimum: 1\nMaximum: 31,The minimum and maximum values for the feature...,1.0,3.100000e+01,1.00,3.100000e+01,NaN,NaN,0.000000,0.000000,NaN
21,week_day,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Dataset: \n\nweek_day: [1 2 3 4 5 6 7]\n\nMini...,Minimum: 1\nMaximum: 7,min: Monday\nmax: Sunday,NaN,NaN,1.00,7.000000e+00,NaN,NaN,NaN,0.000000,NaN
22,avail0,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,NaN,Minimum: 0\nMaximum: 1,"For the feature ""avail0"" in the sales dataset ...",NaN,NaN,0.00,1.000000e+00,NaN,NaN,NaN,1.000000,NaN
23,avail1,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,Based on the available dataset the minimum and...,Minimum: 0\nMaximum: 1,min(avail1): 0\nmax(avail1): 1,NaN,NaN,0.00,1.000000e+00,NaN,NaN,NaN,1.000000,NaN
24,avail2,42183,dataset_sales,numeric,0.000000e+00,1.000000e+00,Dataset sales,min: 0 max: 1,Minimum: 0\nMaximum: 1,min: avail2 = min value in the dataset sales\n...,0.0,1.000000e+00,0.00,1.000000e+00,2.000000,2.000000e+00,1.000000,1.000000,NaN
25,sales,42183,dataset_sales,numeric,3.000000e+00,8.500000e+01,Dataset sales,Minimum: 0\nMaximum: 1000000,Minimum: 0\nMaximum: Unknown,The minimum and maximum values for the feature...,0.0,1.000000e+06,NaN,NaN,NaN,NaN,0.000082,NaN,NaN
26,stdv,42183,dataset_sales,numeric,0.000000e+00,4.700000e+01,Dataset sales,min stdv: 0.1\nmax stdv: 4.5,Minimum value: 0.0\nMaximum value: 1.0,For the feature stdv the minimum value is 0 an...,0.1,4.500000e+00,0.00,1.000000e+00,NaN,NaN,0.093617,0.021277,NaN
27,qts,42545,stock_fardamento02,numeric,1.000000e+00,8.330000e+02,**Author**: \n\n**Source**: Unknown - Date u...,Minimum: 0\nMaximum: 100,Min: Unknown\nMax: Unknown,min: 0\nmax: unknown,0.0,1.000000e+02,NaN,NaN,NaN,NaN,0.118848,NaN,NaN
28,Material,42545,stock_fardamento02,numeric,5.367000e+03,6.502400e+04,**Author**: \n\n**Source**: Unknown - Date u...,Min: 1\nMax: 10,Minimum: Unknown\nMaximum: Unknown,"Sorry, but I can't generate a range of values ...",1.0,1.000000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,pp,42545,stock_fardamento02,numeric,0.000000e+00,2.010000e+01,**Author**: \n\n**Source**: Unknown - Date u...,Range: 0 to 1000,Minimum: unknown\nMaximum: unknown,"pp: min = Unknown, max = Unknown",0.0,1.000000e+03,NaN,NaN,NaN,NaN,0.020100,NaN,NaN
30,TEMP,42545,stock_fardamento02,numeric,8.400000e+00,2.600000e+01,**Author**: \n\n**Source**: Unknown - Date u...,Minimum: -10°C\nMaximum: 40°C,The range of values for the feature TEMP in th...,"TEMP: min = unknown, max = unknown",-10.0,4.000000e+01,NaN,NaN,NaN,NaN,0.352000,NaN,NaN
31,adm,42545,stock_fardamento02,numeric,2.800000e+01,2.300000e+02,**Author**: \n\n**Source**: Unknown - Date u...,Minimum: 0\nMaximum: 100,Minimum: Unknown\nMaximum: Unknown,"The range of values for the feature ""adm"" is m...",0.0,1.000000e+02,NaN,NaN,NaN,NaN,0.313043,NaN,NaN
32,Dem,42545,stock_fardamento02,numeric,3.600000e+01,2.390000e+02,**Author**: \n\n**Source**: Unknown - Date u...,Min: 0 \nMax: 100,"min(Dem) = ???, max(Dem) = ???","The range of values for the feature ""Dem"" is n...",0.0,1.000000e+02,NaN,NaN,NaN,NaN,0.267782,NaN,NaN
33,1990,43809,GDP-per-capita-all-countries,numeric,4.248240e+02,7.290652e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: unknown\nMaximum: unknown,"1990: [unknown minimum value, unknown maximum ...","To set a range of values for the feature ""1990...",NaN,NaN,NaN,NaN,1990.000000,1.990000e+03,NaN,NaN,0.000000
34,1991,43809,GDP-per-capita-all-countries,numeric,3.246360e+02,7.175373e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1900\nMaximum: 2021,1991: Min Value = 1991 Max Value = 1991,min: 1991\nmax: 2019,1900.0,2.021000e+03,NaN,NaN,1991.000000,2.019000e+03,0.001694,NaN,0.000392
35,1992,43809,GDP-per-capita-all-countries,numeric,3.009790e+02,7.156783e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum value: 0\nMaximum value: 1000,Minimum: 1992\nMaximum: 1992,The dataset provides the GDP values for the ye...,0.0,1.000000e+03,1992.00,1.992000e+03,1992.000000,1.992000e+03,0.009767,0.000000,0.000000
36,1993,43809,GDP-per-capita-all-countries,numeric,3.273412e+02,7.008239e+04,Gross Domestic Product (GDP) is the monetary v...,NaN,Minimum: 1993\nMaximum: 1993,"The range of values for the feature ""1993"" is ...",NaN,NaN,1993.00,1.993000e+03,NaN,NaN,NaN,0.000000,NaN
37,1994,43809,GDP-per-capita-all-countries,numeric,3.424329e+02,7.247169e+04,Gross Domestic Product (GDP) is the monetary v...,1994: min = 0 max = 99999999,Minimum: 1994\nMaximum: 1994,The range of values for the feature 1994 in th...,NaN,NaN,1994.00,1.994000e+03,NaN,NaN,NaN,0.000000,NaN
38,1995,43809,GDP-per-capita-all-countries,numeric,3.451363e+02,7.499438e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1995\nMaximum: 1995,Minimum: 1995\nMaximum: 1995,min: 1995\nmax: 1995,1995.0,1.995000e+03,1995.00,1.995000e+03,1995.000000,1.995000e+03,0.000000,0.000000,0.000000
39,1996,43809,GDP-per-capita-all-countries,numeric,3.791511e+02,7.684879e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1\nMaximum: 9999,Minimum: 1996\nMaximum: 1996,"The range of values for the feature ""1996"" in ...",1.0,9.999000e+03,1996.00,1.996000e+03,NaN,NaN,0.125181,0.000000,NaN
40,1997,43809,GDP-per-capita-all-countries,numeric,4.178392e+02,8.039006e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1997\nMaximum: 1997,1997: min = 1997 max = 1997.,min: 1997\nmax: 1997,1997.0,1.997000e+03,NaN,NaN,1997.000000,1.997000e+03,0.000000,NaN,0.000000
41,1998,43809,GDP-per-capita-all-countries,numeric,4.526621e+02,7.742111e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 10000,Minimum: 1998\nMaximum: 1998,Min: 1998\nMax: 1998,0.0,1.000000e+04,1998.00,1.998000e+03,1998.000000,1.998000e+03,0.123317,0.000000,0.000000
42,1999,43809,GDP-per-capita-all-countries,numeric,4.691280e+02,7.665426e+04,Gross Domestic Product (GDP) is the monetary v...,Min: 1990\nMax: 2010,1999: min=1999 max=1999,The minimum and maximum values for the feature...,1990.0,2.010000e+03,NaN,NaN,NaN,NaN,0.000263,NaN,NaN
43,2000,43809,GDP-per-capita-all-countries,numeric,4.558151e+02,8.616939e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1500\nMaximum: 2500,Minimum: 2000\nMaximum: 2019,The range of values for the feature 2000 from ...,1500.0,2.500000e+03,2000.00,2.019000e+03,NaN,NaN,0.011667,0.000222,NaN
44,2001,43809,GDP-per-capita-all-countries,numeric,4.435747e+02,8.813842e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 1\nMaximum: 3000,Minimum: 2001 \nMaximum: 2001,The minimum and maximum values for the feature...,1.0,3.000000e+03,2001.00,2.001000e+03,NaN,NaN,0.029005,0.000000,NaN
45,2002,43809,GDP-per-capita-all-countries,numeric,4.504504e+02,9.209128e+04,Gross Domestic Product (GDP) is the monetary v...,Min: 0\nMax: 100,Minimum: 2002\nMaximum: 2002,The range of values for the feature 2002 is: M...,0.0,1.000000e+02,2002.00,2.002000e+03,NaN,NaN,NaN,0.000000,NaN
46,2003,43809,GDP-per-capita-all-countries,numeric,4.697704e+02,9.145161e+04,Gross Domestic Product (GDP) is the monetary v...,2003: Minimum value: unknown. Maximum value: u...,Minimum: 2003\nMaximum: 2003,Based on the dataset provided the range of val...,NaN,NaN,2003.00,2.003000e+03,NaN,NaN,NaN,0.000000,NaN
47,2004,43809,GDP-per-capita-all-countries,numeric,4.989799e+02,1.013295e+05,Gross Domestic Product (GDP) is the monetary v...,NaN,Minimum: 2004\nMaximum: 2004,Min: 2004\nMax: 2004,NaN,NaN,2004.00,2.004000e+03,2004.000000,2.004000e+03,NaN,0.000000,0.000000
48,2005,43809,GDP-per-capita-all-countries,numeric,5.289748e+02,9.776857e+04,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100,Minimum: 2005\nMaximum: 2005,Min: 2005\nMax: 2005,0.0,1.000000e+02,2005.00,2.005000e+03,2005.000000,2.005000e+03,NaN,0.000000,0.000000
49,2006,43809,GDP-per-capita-all-countries,numeric,5.558000e+02,1.075415e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 1000000,Minimum: 2006\nMaximum: 2006,The min and max values for the feature 2006 fr...,0.0,1.000000e+06,2006.00,2.006000e+03,NaN,NaN,0.106986,0.000000,NaN
50,2007,43809,GDP-per-capita-all-countries,numeric,5.869953e+02,1.093625e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 2007\nMaximum: 2007,Minimum: 2007\nMaximum: 2007,Min: 485415.9\nMax: 21345493.9,2007.0,2.007000e+03,2007.00,2.007000e+03,485415.900000,2.134549e+07,0.000000,0.000000,NaN
51,2008,43809,GDP-per-capita-all-countries,numeric,6.150720e+02,1.112560e+05,Gross Domestic Product (GDP) is the monetary v...,"The minimum value for the feature ""2008"" is: u...",Minimum: 2008\nMaximum: 2008,Min: 2008\nMax: 2008,NaN,NaN,2008.00,2.008000e+03,2008.000000,2.008000e+03,NaN,0.000000,0.000000
52,2009,43809,GDP-per-capita-all-countries,numeric,6.166586e+02,1.089537e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100000,Min: 2009\nMax: 2009,Based on the given dataset the range of values...,0.0,1.000000e+05,2009.00,2.009000e+03,NaN,NaN,0.912161,0.000000,NaN
53,2010,43809,GDP-per-capita-all-countries,numeric,6.462954e+02,1.175187e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100000,2010: min = 2010 max = 2010,Based on the given dataset description we can ...,0.0,1.000000e+05,NaN,NaN,2010.000000,2.010000e+03,0.845429,NaN,0.000000
54,2011,43809,GDP-per-capita-all-countries,numeric,6.820073e+02,1.240246e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 99999,Minimum: 2011\nMaximum: 2011,Min: 2011 Max: 2011,0.0,9.999900e+04,2011.00,2.011000e+03,2011.000000,2.011000e+03,0.800785,0.000000,0.000000
55,2012,43809,GDP-per-capita-all-countries,numeric,7.199143e+02,1.266184e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100,Minimum: 2012\nMaximum: 2012,"The range of values for the feature ""2012"" in ...",0.0,1.000000e+02,2012.00,2.012000e+03,NaN,NaN,NaN,0.000000,NaN
56,2013,43809,GDP-per-capita-all-countries,numeric,6.995929e+02,1.399622e+05,Gross Domestic Product (GDP) is the monetary v...,Min: 0\nMax: 100,Minimum: 2013\nMaximum: 2013,"The range of values for the feature ""2013"" can...",0.0,1.000000e+02,2013.00,2.013000e+03,NaN,NaN,NaN,0.000000,NaN
57,2014,43809,GDP-per-capita-all-countries,numeric,7.108122e+02,1.378330e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100,Minimum: 2014\nMaximum: 2014,"The range of values for the feature ""2014"" in ...",0.0,1.000000e+02,2014.00,2.014000e+03,2014.000000,2.014000e+03,NaN,0.000000,0.000000
58,2015,43809,GDP-per-capita-all-countries,numeric,7.447345e+02,1.238221e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100,Minimum: 2015\nMaximum: 2015,"The range of values for the feature ""2015"" in ...",0.0,1.000000e+02,2015.00,2.015000e+03,NaN,NaN,NaN,0.000000,NaN
59,2016,43809,GDP-per-capita-all-countries,numeric,7.439036e+02,1.235736e+05,Gross Domestic Product (GDP) is the monetary v...,Minimum: Unknown\nMaximum: Unknown,Minimum: 2016\nMaximum: 2016,"The range of values for the feature ""2016"" in ...",NaN,NaN,2016.00,2.016000e+03,NaN,NaN,NaN,0.000000,NaN
60,2017,43809,GDP-per-capita-all-countries,numeric,7.379786e+02,1.246093e+05,Gross Domestic Product (GDP) is the monetary v...,min: 0\nmax: 100,Min: 2017\nMax: 2017,To set a range of values for the feature 2017 ...,0.0,1.000000e+02,2017.00,2.017000e+03,NaN,NaN,NaN,0.000000,NaN
61,2018,43809,GDP-per-capita-all-countries,numeric,7.441821e+02,1.268984e+05,Gross Domestic Product (GDP) is the monetary v...,The minimum and maximum values for the feature...,Min: 2018 Max: 2018,Min: 1990\nMax: 2019,NaN,NaN,2018.00,2.018000e+03,1990.000000,2.019000e+03,NaN,0.000000,0.000230
62,2019,43809,GDP-per-capita-all-countries,numeric,NaN,NaN,Gross Domestic Product (GDP) is the monetary v...,Minimum: 0\nMaximum: 100000,Min: 2019\nMax: 2019,To determine the range of values for the featu...,0.0,1.000000e+05,2019.00,2.019000e+03,NaN,NaN,0.000000,0.000000,NaN
63,Unnamed:_0,43825,Nutritional-values-for-common-foods-and-products,numeric,0.000000e+00,8.788000e+03,Context\nI found this data occasionally and I ...,min: -∞\nmax: +∞,Minimum: 0\nMaximum: Unknown,"The range of values for the feature ""Unnamed:_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,calories,43825,Nutritional-values-for-common-foods-and-products,numeric,0.000000e+00,9.020000e+02,Context\nI found this data occasionally and I ...,Minimum: 0\nMaximum: 5000,"min(calories), max(calories)","The range of values for the feature ""calories""...",0.0,5.000000e+03,NaN,NaN,NaN,NaN,0.180400,NaN,NaN
65,lucopene,43825,Nutritional-values-for-common-foods-and-products,numeric,0.000000e+00,0.000000e+00,Context\nI found this data occasionally and I ...,Minimum: 0\nMaximum: 5000,Minimum: 0\nMaximum: Unknown (Not provided in ...,Min: 0.0\n\nMax: 2181.0,0.0,5.000000e+03,NaN,NaN,0.000000,2.181000e+03,0.000000,NaN,0.000000
66,Year,43831,Consumer-Price-Index,numeric,2.013000e+03,2.020000e+03,Consumer Price Indices (CPI) measure changes o...,Min: 2000 Max: 2021,Minimum: Year 0 (assuming it starts from year ...,"Based on the provided dataset, the range of va...",2000.0,2.021000e+03,NaN,NaN,NaN,NaN,0.333333,NaN,NaN
67,Cereals_and_products,43831,Consumer-Price-Index,numeric,1.075000e+02,1.527000e+02,Consumer Price Indices (CPI) measure changes o...,Minimum: 0\nMaximum: 100,"Min: 0, Max: Unlimited",Min: 0.00 \nMax: 600.00,0.0,1.000000e+02,NaN,NaN,0.000000,6.000000e+02,NaN,NaN,0.075333
68,Meat_and_fish,43831,Consumer-Price-Index,numeric,1.063000e+02,1.970000e+02,Consumer Price Indices (CPI) measure changes o...,Minimum: 0\nMaximum: 10000,Minimum: 0\nMaximum: Not provided,"Min: The minimum value for the feature ""Meat_a...",0.0,1.000000e+04,NaN,NaN,NaN,NaN,0.009070,NaN,NaN
69,Egg,43831,Consumer-Price-Index,numeric,1.027000e+02,1.570000e+02,Consumer Price Indices (CPI) measure changes o...,Minimum: 0\nMaximum: 200,Minimum: 0\nMaximum: Unknown,"The range of values for the feature ""Egg"" in t...",0.0,2.000000e+02,NaN,NaN,NaN,NaN,0.271500,NaN,NaN
70,Milk_and_products,43831,Consumer-Price-Index,numeric,1.036000e+02,1.556000e+02,Consumer Price Indices (CPI) measure changes o...,Minimum: 0\nMaximum: 30000,Minimum: 0 \nMaximum: Unknown,Min: 0\nMax: 100,0.0,3.000000e+04,NaN,NaN,0.000000,1.000000e+02,0.001733,NaN,NaN

In [32]:
eins= df.just_feature_min_value.dropna().sort_values()
zwei = df.all_feature_min_value.dropna().sort_values()
drei = df.all_feature_min_value_desc.dropna().sort_values()
grund_min = df.dataset_min_value.dropna().sort_values()

In [35]:
grund_min[6:-1]

365   -7.499611e+01
366   -7.499401e+01
364   -7.499187e+01
362   -7.498643e+01
363   -7.498539e+01
336   -6.336000e+01
117   -4.810000e+01
109   -4.170000e+01
128   -4.102300e+01
97    -4.080000e+01
119   -3.860000e+01
95    -3.750000e+01
3     -3.403520e+01
2     -3.141300e+01
105   -3.130000e+01
103   -3.090000e+01
107   -3.060000e+01
101   -2.740000e+01
113   -2.470000e+01
99    -2.350000e+01
0     -2.328390e+01
111   -2.130000e+01
1     -1.639350e+01
115   -1.450000e+01
4     -1.203910e+01
211   -1.180634e+01
334   -1.056000e+01
394   -6.557422e+00
231   -6.311427e+00
251   -5.256000e+00
412   -4.578622e+00
426   -4.407334e+00
418   -4.364381e+00
299   -4.325500e+00
431   -4.113898e+00
414   -4.085853e+00
423   -4.076485e+00
424   -4.050889e+00
435   -4.006246e+00
442   -4.004914e+00
421   -3.998474e+00
406   -3.979526e+00
436   -3.937435e+00
413   -3.903017e+00
427   -3.848386e+00
402   -3.844106e+00
430   -3.832277e+00
432   -3.829966e+00
403   -3.828703e+00
434   -3.813526e+00
420   -3.806062e+00
411   -3.798011e+00
439   -3.781449e+00
405   -3.780620e+00
433   -3.776095e+00
425   -3.747531e+00
398   -3.741948e+00
440   -3.714059e+00
419   -3.712649e+00
429   -3.706062e+00
409   -3.673687e+00
401   -3.653304e+00
404   -3.650459e+00
408   -3.617918e+00
416   -3.577676e+00
437   -3.559484e+00
438   -3.550759e+00
443   -3.526863e+00
422   -3.510998e+00
415   -3.503835e+00
410   -3.434010e+00
441   -3.388576e+00
428   -3.357140e+00
417   -3.329408e+00
407   -3.286132e+00
343   -3.057045e+00
397   -3.046482e+00
217   -3.000000e+00
400   -2.917722e+00
396   -2.743479e+00
399   -2.732906e+00
395   -2.372783e+00
352   -2.356192e+00
353   -2.356155e+00
355   -2.356149e+00
351   -2.356092e+00
350   -2.355979e+00
360   -2.355918e+00
354   -2.355893e+00
356   -2.355884e+00
359   -2.355764e+00
361   -2.355641e+00
358   -2.355579e+00
357   -2.355378e+00
300   -1.206000e+00
259   -1.099000e+00
132   -3.980000e-01
382   -1.135172e-01
201    0.000000e+00
268    0.000000e+00
175    0.000000e+00
273    0.000000e+00
176    0.000000e+00
193    0.000000e+00
272    0.000000e+00
271    0.000000e+00
267    0.000000e+00
194    0.000000e+00
269    0.000000e+00
196    0.000000e+00
270    0.000000e+00
260    0.000000e+00
187    0.000000e+00
200    0.000000e+00
189    0.000000e+00
185    0.000000e+00
462    0.000000e+00
221    0.000000e+00
275    0.000000e+00
304    0.000000e+00
333    0.000000e+00
298    0.000000e+00
335    0.000000e+00
297    0.000000e+00
338    0.000000e+00
223    0.000000e+00
174    0.000000e+00
222    0.000000e+00
237    0.000000e+00
238    0.000000e+00
339    0.000000e+00
292    0.000000e+00
274    0.000000e+00
341    0.000000e+00
342    0.000000e+00
241    0.000000e+00
290    0.000000e+00
243    0.000000e+00
244    0.000000e+00
245    0.000000e+00
289    0.000000e+00
286    0.000000e+00
283    0.000000e+00
277    0.000000e+00
250    0.000000e+00
276    0.000000e+00
253    0.000000e+00
291    0.000000e+00
172    0.000000e+00
133    0.000000e+00
116    0.000000e+00
456    0.000000e+00
455    0.000000e+00
454    0.000000e+00
453    0.000000e+00
452    0.000000e+00
451    0.000000e+00
450    0.000000e+00
449    0.000000e+00
448    0.000000e+00
447    0.000000e+00
446    0.000000e+00
63     0.000000e+00
64     0.000000e+00
65     0.000000e+00
94     0.000000e+00
96     0.000000e+00
98     0.000000e+00
100    0.000000e+00
102    0.000000e+00
104    0.000000e+00
106    0.000000e+00
108    0.000000e+00
110    0.000000e+00
457    0.000000e+00
112    0.000000e+00
458    0.000000e+00
459    0.000000e+00
5      0.000000e+00
6      0.000000e+00
7      0.000000e+00
8      0.000000e+00
9      0.000000e+00
10     0.000000e+00
11     0.000000e+00
12     0.000000e+00
13     0.000000e+00
14     0.000000e+00
15     0.000000e+00
16     0.000000e+00
17     0.000000e+00
18     0.000000e+00
19     0.000000e+00
20     0.000000e+00
21     0.000000e+00
22     0.000000e+00
23     0.000000e+00
24     0.000000e+00
461    0.000000e+00
26     0.000000e+00
460    0.000000e+00
29     0.000000e+00
114    0.000000e+00
266    0.000000e+00
152    0.000000e+00
383    0.000000e+00
390    0.000000e+00
391    0.000000e+00
393    0.000000e+00
118    0.000000e+00
136    0.000000e+00
134    0.000000e+00
137    0.000000e+00
131    0.000000e+00
127    0.000000e+00
125    0.000000e+00
123    0.000000e+00
121    0.000000e+00
120    0.000000e+00
265    0.000000e+00
173    2.810000e-07
166    2.844950e-04
169    2.844950e-04
168    2.844950e-04
167    2.844950e-04
165    2.844950e-04
156    2.844950e-04
161    2.844950e-04
159    2.844950e-04
163    2.891850e-04
160    2.891850e-04
158    2.891850e-04
170    2.891850e-04
164    2.891850e-04
162    2.907820e-04
155    2.907820e-04
157    2.907820e-04
301    5.000000e-04
171    5.415358e-03
177    1.428571e-02
386    9.250000e-02
150    1.000000e-01
144    1.000000e-01
147    1.000000e-01
139    1.370000e-01
381    2.500365e-01
370    2.500787e-01
379    2.500824e-01
375    2.500895e-01
368    2.500922e-01
373    2.501434e-01
377    2.501547e-01
372    2.502136e-01
367    2.503663e-01
374    2.504344e-01
380    2.504841e-01
369    2.505092e-01
376    2.505210e-01
378    2.506534e-01
371    2.507491e-01
463    4.400000e-01
261    4.440000e-01
294    5.000000e-01
142    5.260000e-01
249    8.039000e-01
257    8.630000e-01
255    9.570000e-01
146    9.900000e-01
27     1.000000e+00
233    1.000000e+00
242    1.000000e+00
234    1.000000e+00
235    1.000000e+00
236    1.000000e+00
303    1.000000e+00
179    1.000000e+00
218    1.000000e+00
239    1.000000e+00
240    1.000000e+00
302    1.000000e+00
246    1.000000e+00
154    1.000000e+00
130    1.000000e+00
228    1.000000e+00
258    1.000000e+00
180    1.000000e+00
227    1.000000e+00
337    1.000000e+00
220    1.000000e+00
279    1.000000e+00
181    1.000000e+00
340    1.000000e+00
284    1.000000e+00
285    1.000000e+00
247    1.000000e+00
281    1.000000e+00
256    1.022000e+00
293    1.118000e+00
141    1.144000e+00
149    1.188000e+00
135    1.398000e+00
263    1.467000e+00
252    1.544000e+00
210    1.713911e+00
219    2.000000e+00
248    2.000000e+00
312    2.000000e+00
280    2.000000e+00
278    2.000000e+00
332    2.000000e+00
331    2.000000e+00
330    2.000000e+00
329    2.000000e+00
328    2.000000e+00
262    2.267000e+00
209    2.554261e+00
225    3.000000e+00
178    3.000000e+00
315    3.000000e+00
25     3.000000e+00
346    3.135494e+00
345    3.637586e+00
316    4.000000e+00
318    4.000000e+00
254    4.174000e+00
344    4.369448e+00
264    4.917000e+00
327    5.000000e+00
326    5.000000e+00
313    5.000000e+00
317    6.000000e+00
311    6.000000e+00
314    7.000000e+00
347    7.586804e+00
148    7.700000e+00
320    8.000000e+00
30     8.400000e+00
319    9.000000e+00
208    9.891578e+00
387    1.031010e+01
182    1.100000e+01
214    1.111076e+01
215    1.147023e+01
186    1.158000e+01
224    1.200000e+01
321    1.400000e+01
325    1.500000e+01
322    1.500000e+01
140    1.510000e+01
392    1.522800e+01
306    1.600000e+01
323    1.800000e+01
184    1.800000e+01
197    1.800000e+01
190    1.800000e+01
296    2.000000e+01
287    2.000000e+01
288    2.000000e+01
295    2.000000e+01
324    2.500000e+01
31     2.800000e+01
389    3.197040e+01
32     3.600000e+01
202    3.762592e+01
212    3.952043e+01
206    4.697947e+01
309    4.700000e+01
226    4.800000e+01
310    4.900000e+01
308    4.900000e+01
232    4.991562e+01
192    5.000000e+01
199    5.000000e+01
151    5.328000e+01
205    6.027031e+01
444    6.400000e+01
445    6.500000e+01
145    7.937000e+01
203    8.306982e+01
75     8.530000e+01
84     1.003000e+02
71     1.011000e+02
73     1.014000e+02
76     1.018000e+02
91     1.021000e+02
72     1.023000e+02
69     1.027000e+02
89     1.029000e+02
88     1.032000e+02
90     1.035000e+02
74     1.035000e+02
70     1.036000e+02
92     1.037000e+02
93     1.040000e+02
87     1.040000e+02
77     1.048000e+02
86     1.048000e+02
82     1.050000e+02
80     1.051000e+02
85     1.054000e+02
79     1.055000e+02
83     1.058000e+02
81     1.059000e+02
68     1.063000e+02
78     1.067000e+02
67     1.075000e+02
204    1.340193e+02
307    1.550000e+02
35     3.009790e+02
34     3.246360e+02
36     3.273412e+02
37     3.424329e+02
38     3.451363e+02
183    3.500000e+02
39     3.791511e+02
385    4.035000e+02
40     4.178392e+02
33     4.248240e+02
44     4.435747e+02
45     4.504504e+02
41     4.526621e+02
43     4.558151e+02
42     4.691280e+02
46     4.697704e+02
47     4.989799e+02
305    5.000000e+02
48     5.289748e+02
49     5.558000e+02
50     5.869953e+02
51     6.150720e+02
52     6.166586e+02
53     6.462954e+02
143    6.612400e+02
54     6.820073e+02
56     6.995929e+02
57     7.108122e+02
55     7.199143e+02
60     7.379786e+02
59     7.439036e+02
61     7.441821e+02
58     7.447345e+02
138    8.090000e+02
191    9.500000e+02
198    9.500000e+02
282    1.001000e+03
207    1.509553e+03
153    1.950000e+03
66     2.013000e+03
195    2.018000e+03
188    2.018000e+03
384    2.392050e+03
213    3.406968e+03
28     5.367000e+03
230    1.062800e+04
229    9.060900e+04
388    3.194902e+05
Name: dataset_min_value, dtype: float64

In [91]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots


fig = make_subplots(rows=3, cols=1,subplot_titles=("Just Feature Min Value","All Feature Min Value","All Feature and Description Min Value"),x_title="Values From ChatGPT Answers", 
                    y_title="Frequency of Values")

Experiment1 = go.Histogram(x=eins[4:-14], nbinsx=60, )
Experiment2 = go.Histogram(x=zwei[3:-33], nbinsx = 60)
Experiment3 = go.Histogram(x=drei[5:-20], nbinsx=60)
#Min = go.Histogram(x=grund_min[10:-30], nbinsx=60 )


fig.append_trace(Experiment1, 1, 1)
#fig.add_trace(Min, 1, 1)
fig.append_trace(Experiment2, 2, 1)
#fig.add_trace(Min, 2, 1)
fig.append_trace(Experiment3, 3, 1)
#fig.add_trace(Min, 3, 1)

fig.update_xaxes(showline=True, linewidth=1, linecolor='black', mirror=True)
fig.update_yaxes(showline=True, linewidth=1, linecolor='black', mirror=True)
fig.update_layout(showlegend=False,barmode='overlay')

#fig.update_traces(opacity=0.5)

fig.write_image("min_values_test.pdf")

In [25]:
vier = df.just_feature_max_value.dropna().sort_values()
fünf = df.all_feature_max_value.dropna().sort_values()
sechs = df.all_feature_max_value_desc.dropna().sort_values()

In [105]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots


fig = make_subplots(rows=3, cols=1,subplot_titles=("Just Feature Max Value","All Feature Max Value","All Feature and Description Max Value"),x_title="Values From ChatGPT Answers", 
                    y_title="Frequency of Values")

trace0 = go.Histogram(x=vier[:-50], nbinsx=60)
trace1 = go.Histogram(x=fünf[:-50], nbinsx = 60)
trace2 = go.Histogram(x=sechs[:-31], nbinsx=60 )


fig.append_trace(trace0, 1, 1)
fig.append_trace(trace1, 2, 1)
fig.append_trace(trace2, 3, 1)

fig.update_xaxes(showline=True, linewidth=1, linecolor='black', mirror=True)
fig.update_yaxes(showline=True, linewidth=1, linecolor='black', mirror=True)
fig.update_layout(showlegend=False)

fig.write_image("max_values_test.pdf")

In [109]:
import plotly.graph_objects as go
animals=['Just Feature', 'All Feature', 'Just Feature and Description']

fig = go.Figure([go.Bar(x=animals, y=[a.mean(), b.mean(), c.mean()],text=[np.round(a.mean(),2), np.round(b.mean(),2), np.round(c.mean(),2)],
            textposition='auto'),])
fig.update_layout(yaxis_range=[0,1],title_text='JI Values of the Three Experiments')
fig.update_xaxes(showline=True, linewidth=2, linecolor='black', mirror=True)
fig.update_yaxes(showline=True, linewidth=2, linecolor='black', mirror=True)
fig.write_image("bar_test.pdf")